language: python

python:
  - 2.7
  - 3.5
  - 3.4
  - 3.3

# Use container-based infrastructure
sudo: false

install:
  - travis_retry pip install pyflakes

script:
  - pyflakes build.sh

after_success:
  - travis_retry pip install pep8
  - pep8 --statistics --count build.sh

matrix:
  fast_finish: true

  allow_failures:
    - python: 3.5
    - python: 3.4
    - python: 3.3

notifications:
  email: false
